name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile main.py
          # Rename output so it’s unique per OS
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            mv dist/main.exe dist/myapp-windows.exe
          elif [[ "${{ runner.os }}" == "Linux" ]]; then
            mv dist/main dist/myapp-linux
          else
            mv dist/main dist/myapp-macos
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: dist/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release_builds

      - name: List files (debugging)
        run: ls -R ./release_builds

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release_builds/**/myapp-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}