name: Build and Release

on:
  push:
    tags:
      - 'v*'   # Trigger on version tags like v1.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            ext: exe
          - os: ubuntu-latest
            ext: ""
          - os: macos-latest
            ext: ""
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile main.py

      - name: Rename executable
        run: |
          mkdir renamed
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv dist/your_script.exe renamed/gameorganiser-windows.exe
          elif [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            mv dist/your_script renamed/gameorganiser-linux
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            mv dist/your_script renamed/gameorganiser-macos
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: renamed/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release_builds

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release_builds/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
