name: Build and Release

on:
  push:
    tags:
      - '*'   # accepts both v1.0.0 and 1.0.0
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: windows
            ext: exe
          - os: ubuntu-latest
            name: linux
            ext: ""
          - os: macos-latest
            name: macos
            ext: ""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          
      - name: Build executable
        run: pyinstaller --onefile main.py

      - name: Rename executable
        run: |
          mkdir renamed
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv dist/main.exe renamed/gameorganiser-${{ matrix.name }}.exe
          else
            mv dist/main renamed/gameorganiser-${{ matrix.name }}
            chmod +x renamed/gameorganiser-${{ matrix.name }}
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.name }}
          path: renamed/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release_builds

      - name: List files (debugging)
        run: ls -R ./release_builds

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release_builds/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
