name: Build and Release

on:
  push:
    tags:
      - 'v*'   # Runs only when you push a version tag like v1.0.0
  workflow_dispatch: # Allow manual trigger too

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile main.py

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: dist/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release_builds

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release_builds/**/*
        env:
          GITHUB_TOKEN: ${{ test.GH_PAT }}
